<a href="https://colab.research.google.com/github/answjddn005/Pytorch-Practice/blob/main/DL%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf

import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10 

X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()

print("Y(tensorflow): \n", Y_tf.numpy())

z = matmul(X, W) + B
Y_man_matmul = 1/(1 + exp(-z))

print("Y(with matmul):\n", Y_man_matmul.numpy())

Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z = tf.reduce_sum(x * w) + b
    a = 1/(1 +np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products): \n", Y_man_vec)

Y(tensorflow): 
 [[0.9160638  0.92377216 0.3755081 ]
 [0.27800018 0.26821098 0.36862057]
 [0.4827083  0.78619206 0.48585546]
 [0.49566472 0.34335482 0.89656895]]
Y(with matmul):
 [[0.9160637  0.9237721  0.37550813]
 [0.2780002  0.26821095 0.36862054]
 [0.48270833 0.78619206 0.48585543]
 [0.49566472 0.3433548  0.8965689 ]]
Y(with dot products): 
 [[0.91606376 0.92377215 0.37550808]
 [0.27800019 0.26821095 0.36862057]
 [0.48270829 0.78619203 0.48585541]
 [0.49566473 0.34335479 0.89656894]]


In [24]:
n_neurons = [3, 5]

dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

A1 = dense1(X)
Y = dense2(A1)

W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print("X: {}\n".format(X.shape))

print("W1: ", W1.shape)
print("B1: ", B1.shape)

print("A1: {}\n".format(A1.shape))
print("W2 ", W2.shape)
print("B2, ", B2.shape)

print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2  (3, 5)
B2,  (5,)
Y: (4, 5)



In [37]:
n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
for n_neuron1 in n_neurons:
  dense = Dense(units=n_neuron1, activation='relu')
  dense_layers.append(dense)

print("Input: ", X.shape)
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print("After dense layer ", dense_idx+1)
  print(X.shape, '\n')

Y = X

Input:  (4, 10)
After dense layer  1
(4, 10) 

After dense layer  2
(4, 20) 

After dense layer  3
(4, 30) 

After dense layer  4
(4, 40) 

After dense layer  5
(4, 50) 

After dense layer  6
(4, 60) 

After dense layer  7
(4, 70) 

After dense layer  8
(4, 80) 

After dense layer  9
(4, 90) 

After dense layer  10
(4, 100) 



In [47]:
X_cp = tf.identity(X)

n_neurons = [3, 4, 5]

dense_layers = list()

for n_neuron1 in n_neurons:
  dense = Dense(units=n_neuron1, activation='sigmoid')
  dense_layers.append(dense)

W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)

print("X(tensorflow): ", X.numpy())

for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1 + exp(-X_cp))

print('Y(Maunal): \n', X_cp.numpy())

X(tensorflow):  [[0.32114315 0.48301685 0.3993367  0.57164276 0.4877478 ]
 [0.32114315 0.48301685 0.3993367  0.57164276 0.4877478 ]
 [0.32114315 0.48301685 0.3993367  0.57164276 0.4877478 ]
 [0.32114315 0.48301685 0.3993367  0.57164276 0.4877478 ]]
Y(Maunal): 
 [[0.32114315 0.48301688 0.3993367  0.57164276 0.48774776]
 [0.32114315 0.48301688 0.3993367  0.57164276 0.48774776]
 [0.32114315 0.48301688 0.3993367  0.57164276 0.48774776]
 [0.32114315 0.48301688 0.3993367  0.57164276 0.48774776]]


In [48]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Dense(units=10, activaiton='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

In [52]:
from tensorflow.keras.models import Model
class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

model = TestModel()
print(model.dense1)
print(model.dense2)

In [56]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model


X = tf.random.normal(shape=(4, 10))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

  def call(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    return x

model1 = TestModel()
 Y = model1(X)

[[0.6738721  0.29830164 0.36661482 0.6043039  0.5436932  0.42093182
  0.5881985  0.5396225  0.48334408 0.75441253 0.5121683  0.6150243
  0.4338801  0.5091558  0.52578706 0.6050348  0.3972675  0.47691962
  0.5139247  0.34930134]
 [0.6241122  0.3340735  0.3840988  0.4983276  0.5532251  0.45255008
  0.5420944  0.480397   0.5100609  0.77785134 0.5059263  0.6585937
  0.36498505 0.567686   0.4619151  0.53294784 0.37265906 0.47373942
  0.63384765 0.30350024]
 [0.59918123 0.3912526  0.3533038  0.5213855  0.5315356  0.42013243
  0.55214864 0.53795534 0.4823567  0.7346326  0.52737916 0.6207779
  0.52634287 0.6059091  0.5288371  0.4963849  0.3757424  0.51915556
  0.5696839  0.39041135]
 [0.5765786  0.35097736 0.39352405 0.4541151  0.52313185 0.46564144
  0.5187617  0.4724307  0.59421927 0.727908   0.44994983 0.7012198
  0.3603722  0.554608   0.5029072  0.5541806  0.3940758  0.45050222
  0.6718704  0.2726711 ]]


In [64]:
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(model.layers)
print(type(model.layers))

for layer in model.layers:
  w, b = layer.get_weights()
  print(w.shape, b.shape)

[<keras.layers.core.dense.Dense object at 0x7fe2e0563110>, <keras.layers.core.dense.Dense object at 0x7fe2e0563790>]
<class 'list'>
(10, 10) (10,)
(10, 20) (20,)


In [69]:
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

print(type(model.trainable_variables))
print(len(model.trainable_variables))

for train_var in model.trainable_variables:
  print(train_var.shape)

<class 'list'>
4
(10, 10)
(10,)
(10, 20)
(20,)
